export const ActionTypes = {
    ADD_NEW_TODO:'ADD_NEW_TODO',
    TOGGLE_IMPORTANCE:'TOGGLE_IMPORTANCE',
    DELETE_TODO:'DELETE_TODO',
    CLEAR_ALL_TODOS:'CLEAR_ALL_TODOS',
    CLEAR_COMPLETED:'CLEAR_COMPLETED',
    GET_ALL:'GET_ALL'
}



